# bash completion for p27. Install as `p27` in a bash-completion completions directory,
# or run scripts/install-completion.sh. Do not edit: generated by `p27 completion bash`.
#
# Every candidate comes from `p27 __complete`, which walks the real command tree, so this
# script never has to know what p27's commands are. Plain bash cannot show descriptions,
# so they are stripped here; install fzf and use the `**` trigger to see them.

_p27_completion() {
  local cur cword directive
  local -a words
  local -a lines=()
  local line value

  # bash splits COMP_WORDS on COMP_WORDBREAKS, which includes ':' and '=' — that would
  # shred p27's `uid:5` refs and `--opt=value`. bash-completion's helpers undo it; the
  # fallback below is only for a bash without bash-completion loaded.
  if declare -F _init_completion >/dev/null 2>&1; then
    _init_completion -n ":=" || return
  else
    words=("${COMP_WORDS[@]}")
    cword=$COMP_CWORD
    cur="${COMP_WORDS[COMP_CWORD]}"
    COMPREPLY=()
  fi

  # The committed words plus the word under the cursor (possibly empty), as argv.
  local -a request=("${words[@]:0:cword}" "${words[cword]}")

  # Read here rather than in a helper: a process substitution runs in a subshell, so a
  # directive picked up there would never make it back out.
  while IFS= read -r line; do
    lines+=("$line")
  done < <(p27 __complete -- "${request[@]}" 2>/dev/null)

  directive=":none"
  if (( ${#lines[@]} )); then
    directive="${lines[-1]}"
    unset 'lines[-1]'
  fi

  COMPREPLY=()
  for line in "${lines[@]}"; do
    [[ -n "$line" ]] || continue
    value="${line%%$'\t'*}"
    # printf %q keeps values with spaces ("Alpha Project") a single word on the line.
    COMPREPLY+=("$(printf '%q' "$value")")
  done

  if (( ${#COMPREPLY[@]} == 0 )); then
    case "$directive" in
      :p27files) _p27_files "p27" ;;
      :files) _p27_files ;;
    esac
  fi

  # Values are already prefix-filtered by __complete; a ':' in one still confuses bash's
  # word splitting on the display side.
  if declare -F __ltrim_colon_completions >/dev/null 2>&1; then
    __ltrim_colon_completions "$cur"
  fi
}

# $1: restrict to this extension (bare, no dot). Unset means any file.
_p27_files() {
  if declare -F _filedir >/dev/null 2>&1; then
    _filedir "${1-}"
  else
    # Without bash-completion, offer matching files plus directories to descend into.
    COMPREPLY=($(compgen -f -X "${1:+!*.$1}" -- "$cur") $(compgen -d -S / -- "$cur"))
  fi
}

complete -F _p27_completion p27

# --- fzf ---------------------------------------------------------------------
# With fzf loaded, `p27 --project **<TAB>` opens fzf showing descriptions. __fzf_defc
# wraps the completion registered above and delegates back to it when the `**` trigger is
# absent, so plain TAB keeps working exactly as before.
if declare -F __fzf_defc >/dev/null 2>&1; then
  _fzf_complete_p27() {
    local -a words
    local cword
    if declare -F _init_completion >/dev/null 2>&1; then
      _init_completion -n ":=" 2>/dev/null || true
    else
      words=("${COMP_WORDS[@]}")
      cword=$COMP_CWORD
    fi
    local -a request=("${words[@]:0:cword}" "${words[cword]}")
    _fzf_complete --reverse --with-nth=1 --delimiter='\t' -- "$@" < <(
      p27 __complete -- "${request[@]}" 2>/dev/null | command grep -v '^:'
    )
  }

  # Insert only the value, never the description column.
  _fzf_complete_p27_post() {
    command awk -F '\t' '{print $1}'
  }

  __fzf_defc p27 _fzf_complete_p27 "-o default -o bashdefault"
fi
