{{- if and .Values.server.persistence.enabled (not .Values.server.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "project27.fullname" . }}-server-data
  labels:
    {{- include "project27.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.server.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
{{- end }}
