#!/usr/bin/env bash
# Installs p27 shell completion for bash and/or zsh.
#
# It only ever writes a completion script into a directory the shell already searches.
# It never edits ~/.zshrc, ~/.bashrc or any other startup file — if a directory has to be
# added to $fpath for zsh to find the script, the line to add is printed and left to you.
#
# Usage: install-completion.sh [bash|zsh|all] [--dry-run] [--force] [--uninstall]
#        install-completion.sh --help

set -euo pipefail

P27="${P27:-p27}"
DRY_RUN=0
UNINSTALL=0
FORCE=0
SHELLS=()
NEEDS_FPATH_LINE=""

# Every script `p27 completion` prints carries this line; anything at the target path
# without it was written by someone else and is not ours to overwrite.
GENERATED_MARKER='generated by `p27 completion'

die() { printf 'error: %s\n' "$1" >&2; exit 1; }
is_ours() { [[ -f "$1" ]] && grep -qF "$GENERATED_MARKER" "$1" 2>/dev/null; }
info() { printf '%s\n' "$1"; }
run() { if (( DRY_RUN )); then printf '  would run: %s\n' "$*"; else "$@"; fi; }

usage() {
  sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'
  cat <<'EOF'

Arguments:
  bash|zsh|all   Which shell to install for. Default: the shell you are running.

Options:
  --dry-run      Print what would happen; change nothing.
  --force        Overwrite a completion script this installer did not write.
  --uninstall    Remove previously installed completion scripts.
  --help         This text.

Environment:
  P27            The p27 binary to use. Default: p27 from $PATH.
EOF
}

while (( $# )); do
  case "$1" in
    bash|zsh) SHELLS+=("$1") ;;
    all) SHELLS+=(bash zsh) ;;
    --dry-run) DRY_RUN=1 ;;
    --uninstall) UNINSTALL=1 ;;
    --force) FORCE=1 ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown argument '$1' (try --help)" ;;
  esac
  shift
done

if (( ${#SHELLS[@]} == 0 )); then
  case "$(basename "${SHELL:-}")" in
    zsh) SHELLS=(zsh) ;;
    bash) SHELLS=(bash) ;;
    *) die "cannot tell which shell to target; pass bash, zsh, or all" ;;
  esac
fi

command -v "$P27" >/dev/null 2>&1 \
  || die "'$P27' is not on PATH; install it (dotnet tool install -g Project27.Cli) or set P27=/path/to/p27"

# --- where each shell looks -------------------------------------------------
#
# bash: bash-completion loads $XDG_DATA_HOME/bash-completion/completions/<command> on
#   demand, with no startup-file entry. That is the one location that needs no rc edit,
#   so it is the only one we use.
# zsh: the script must be named _p27 and sit on $fpath. There is no rc-free equivalent of
#   the bash directory, so prefer a writable site-functions dir that is already on $fpath
#   and only fall back to ~/.zfunc (which the user must add themselves).

bash_completion_dir() {
  printf '%s/bash-completion/completions' "${XDG_DATA_HOME:-$HOME/.local/share}"
}

zsh_completion_dir() {
  local dir
  # Ask the user's zsh what is actually on its fpath, and take the first writable
  # site-functions directory. An existing directory we can write to needs no rc change.
  while IFS= read -r dir; do
    case "$dir" in
      */site-functions)
        if [[ -d "$dir" && -w "$dir" ]]; then
          printf '%s' "$dir"
          return 0
        fi
        ;;
    esac
  done < <(zsh -c 'print -l $fpath' 2>/dev/null || true)

  # Nothing writable: fall back to a private directory and report that $fpath needs it.
  NEEDS_FPATH_LINE="$HOME/.zfunc"
  printf '%s' "$HOME/.zfunc"
}

install_one() {
  local shell="$1" dir file
  case "$shell" in
    bash) dir="$(bash_completion_dir)"; file="$dir/p27" ;;
    zsh) dir="$(zsh_completion_dir)"; file="$dir/_p27" ;;
  esac

  if (( UNINSTALL )); then
    if [[ ! -e "$file" ]]; then
      info "nothing to remove for $shell ($file)"
    elif is_ours "$file"; then
      run rm -f "$file"
      info "removed $file"
    else
      info "left $file alone: this installer did not write it"
    fi
    return 0
  fi

  if [[ -e "$file" ]] && ! is_ours "$file" && (( ! FORCE )); then
    cat >&2 <<EOF
error: $file already exists and was not written by this installer.
       Overwriting it would discard someone's own completion script. Inspect it,
       then re-run with --force to replace it (or move it aside yourself).
EOF
    exit 1
  fi

  run mkdir -p "$dir"
  if (( DRY_RUN )); then
    info "would install $shell completion -> $file"
    return 0
  else
    # Generate to a temp file first: a half-written completion script breaks every
    # subsequent TAB in that shell.
    local tmp
    tmp="$(mktemp "${TMPDIR:-/tmp}/p27-completion.XXXXXX")"
    if ! "$P27" completion "$shell" >"$tmp"; then
      rm -f "$tmp"
      die "'$P27 completion $shell' failed"
    fi
    [[ -s "$tmp" ]] || { rm -f "$tmp"; die "'$P27 completion $shell' produced nothing"; }
    mv "$tmp" "$file"
    chmod 0644 "$file"
  fi
  info "installed $shell completion -> $file"
}

for shell in "${SHELLS[@]}"; do
  install_one "$shell"
done

(( UNINSTALL )) && exit 0

# --- what the user still has to do ------------------------------------------

for shell in "${SHELLS[@]}"; do
  if [[ "$shell" == bash ]] && ! bash -lic 'type _init_completion' >/dev/null 2>&1; then
    cat <<'EOF'

note: bash-completion does not look loaded. The script is installed in the directory it
      reads, but it will not load until bash-completion itself does. On macOS:
        brew install bash-completion@2
EOF
  fi
done

if [[ -n "$NEEDS_FPATH_LINE" ]]; then
  cat <<EOF

action required: no writable directory on zsh's \$fpath was found, so the script went to
                 $NEEDS_FPATH_LINE. Add this to ~/.zshrc, above 'compinit':

    fpath=($NEEDS_FPATH_LINE \$fpath)

EOF
fi

cat <<'EOF'

Start a new shell (or `exec $SHELL`) to pick it up.
Install fzf for fuzzy candidates with descriptions: https://github.com/junegunn/fzf
EOF
